# Generated by Django 4.1.4 on 2023-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认姓名', max_length=100)),
                ('phone', models.CharField(default='默认电话号码', max_length=100)),
                ('email', models.EmailField(default='default@example.com', max_length=254)),
                ('message', models.CharField(max_length=100)),
                ('jiaoyubeijing', models.TextField(default='默认教育背景')),
                ('gongzhuojingli', models.TextField(default='默认工作经历')),
                ('xiangmujingli', models.TextField(default='默认项目经历')),
                ('jinengzhengshu', models.TextField(default='默认技能证书')),
                ('file', models.ImageField(default='static/iamges/default.png', upload_to='static/images/')),
            ],
        ),
    ]
