# -*- coding: utf-8 -*-
# time:2023/6/4 16:23
# file demo2.py
# outhor:czy
# email:1060324818@qq.com

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTEST():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tEST(self):
        driver = webdriver.Edge(executable_path='msedgedriver.exe')
        self.driver = driver
        self.driver.get("https://www.mandaoo.com/man_v/12978-0-0.html")
        self.driver.set_window_size(1296, 696)
        self.driver.switch_to.frame(0)
        self.driver.switch_to.frame(0)
        time.sleep(5)
        element = self.driver.find_element(By.CSS_SELECTOR, "#a1 > .dplayer-controller-mask")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#a1 .dplayer-video")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.ID, "a1").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dplayer-icon > svg").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dplayer-icon > svg > path").click()
        self.driver.find_element(By.CSS_SELECTOR, ".dplayer-icon > svg").click()
        html = driver.page_source
        print(html)
        driver.close()


TestTEST().test_tEST()