# Generated by Django 4.1.4 on 2023-07-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xingxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('birthdate', models.CharField(max_length=128, unique=True)),
                ('classname', models.CharField(max_length=128, unique=True)),
                ('hoby', models.CharField(max_length=128, unique=True)),
                ('Personalstrengths', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
