# Generated by Django 4.1.4 on 2023-07-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xingxi',
            options={'verbose_name_plural': '信息'},
        ),
    ]
