# Generated by Django 4.1.4 on 2023-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gongzhuojingli',
            field=models.TextField(default='默认工作经历'),
        ),
        migrations.AddField(
            model_name='contact',
            name='jiaoyubeijing',
            field=models.TextField(default='默认教育背景'),
        ),
        migrations.AddField(
            model_name='contact',
            name='jinengzhengshu',
            field=models.TextField(default='默认技能证书'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='默认电话号码', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='xiangmujingli',
            field=models.TextField(default='默认项目经历'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='默认姓名', max_length=100),
        ),
    ]
