# Generated by Django 4.1.4 on 2023-07-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianli', '0006_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
